### ISSUE TITLE
no module named raspp_tools

### ISSUE THREAD

**Issue by Roger-Hoo3** [RomeroLab/ML-Guided-Acyl-ACP-Reductase-Engineering#2]
report error "no module named raspp_tools" when run ACR_SCHEMA_compiled.py, and no find raspp_tools.py in this project.
When uploading this project to Git, was raspp_tools.py overlooked..? :)

**Comment by philromero** [comment]
I've uploaded raspp_tools.py to the repo

**Comment by Roger-Hoo3** [comment]
> I've uploaded raspp_tools.py to the repo

Thanks for your reply.
